global:
  smtp_smarthost: 'smtp.qq.com:465'  
  smtp_from: '353938339@qq.com' 
  smtp_auth_username: '353938339@qq.com'
  smtp_auth_password: 'xrvcmvqfsgqicadh'
  smtp_hello: '@qq.com'
  smtp_require_tls: false
  
  
route:
   group_by: [alertname] 
   group_wait：10s  
   group_interval: 10s
   repeat_interval: 2m 
   receiver: 'email'
   
receivers:
- name: 'email'
  email_configs:
   - to: '353938339@qq.com'
     send_resolved: true    
     
     
inhibit_rules:
  - source_matchers: [severity="critical"]
    target_matchers: [severity="warning"]
    equal: ['alertname', 'dev', 'instance'] 
    
# 源匹配级别，当匹配成功发出通知，但是其他 'alertname', 'dev', 'instance'产生的waring级别的告警将被抑制 
